"""The test workbook, as literals the suite owns.

Generated by ``tests/_regenerate_fixture.py`` from ``files/vol_marks.xlsx``.
Do not edit by hand: run that script, and commit the diff it makes.

``make_workbook(path)`` writes the whole thing, which is what the shipped file
says today, so a test that used to copy that file and pin numbers off it reads
the same numbers here.  ``make_workbook(path, pairs=("USDJPY", "EURUSD"))``
writes the settings tabs and only those pair sheets, which is the same workbook
as far as the settings go and a much smaller one to load: every reload
calibrates every pair in CONFIG, so a test that only marks USDJPY was paying
for thirteen other smiles on every read.
"""

from __future__ import annotations

import datetime
from pathlib import Path

import openpyxl

#: The pairs CONFIG names in the shipped workbook.
_CONFIG_PAIRS = frozenset({
    'AUDJPY',
    'AUDUSD',
    'EURCNH',
    'EURGBP',
    'EURJPY',
    'EURUSD',
    'GBPCNH',
    'GBPNZD',
    'GBPUSD',
    'NZDUSD',
    'USDCNH',
    'USDCNY',
    'USDHKD',
    'USDJPY',
})

#: Every sheet, in the workbook's own order, as rows of cell values.
SHEETS = {
    'Export Summary': (
        (),
        (),
        (None, 'This document was exported from Numbers. Each table was converted to an Excel worksheet. All other objects on each Numbers sheet were placed on separate worksheets. Please be aware that formula calculations may differ in Excel.'),
        (),
        (),
        (),
        (None, 'Numbers Sheet Name', 'Numbers Table Name', 'Excel Worksheet Name'),
        (),
        (None, 'INDIC_CONFIG'),
        (None, None, 'Table 1', 'INDIC_CONFIG'),
        (None, 'INDIC_CONFIG'),
        (None, None, 'Table 1', 'INDIC_CONFIG'),
        (None, 'CONFIG'),
        (None, None, 'Table 1', 'CONFIG'),
        (None, 'NZDUSD'),
        (None, None, 'Table 1', 'NZDUSD'),
        (None, 'GBPUSD'),
        (None, None, 'Table 1', 'GBPUSD'),
        (None, 'GBPNZD'),
        (None, None, 'Table 1', 'GBPNZD'),
        (None, 'EURGBP'),
        (None, None, 'Table 1', 'EURGBP'),
        (None, 'USDHKD'),
        (None, None, 'Table 1', 'USDHKD'),
        (None, 'GBPCNH'),
        (None, None, 'Table 1', 'GBPCNH'),
        (None, 'AUDCNH'),
        (None, None, 'Table 1', 'AUDCNH'),
        (None, 'NZDCNH'),
        (None, None, 'Table 1', 'NZDCNH'),
        (None, 'CNHHKD'),
        (None, None, 'Table 1', 'CNHHKD'),
        (None, 'EURCNH'),
        (None, None, 'Table 1', 'EURCNH'),
        (None, 'AUDJPY'),
        (None, None, 'Table 1', 'AUDJPY'),
        (None, 'EURJPY'),
        (None, None, 'Table 1', 'EURJPY'),
        (None, 'EURUSD'),
        (None, None, 'Table 1', 'EURUSD'),
        (None, 'AUDUSD'),
        (None, None, 'Table 1', 'AUDUSD'),
        (None, 'USDJPY'),
        (None, None, 'Table 1', 'USDJPY'),
        (None, 'USDCNH'),
        (None, None, 'Table 1', 'USDCNH'),
        (None, 'USDCNY'),
        (None, None, 'Table 1', 'USDCNY'),
        (None, 'PARAMS'),
        (None, None, 'Table 1', 'PARAMS'),
        (None, 'EVENTS'),
        (None, None, 'Table 1', 'EVENTS'),
        (None, 'Vega Weights'),
        (None, None, 'Table 1', 'Vega Weights'),
    ),
    'INDIC_CONFIG': (
        ('indication.xlsx',),
    ),
    'CONFIG': (
        ('PAIRS', 'TENORS'),
        ('USDJPY', '1w'),
        ('USDCNH', '2w'),
        ('USDCNY', '3w'),
        ('EURUSD', '1m'),
        ('GBPUSD', '2m'),
        ('AUDUSD', '3m'),
        ('NZDUSD', '6m'),
        ('EURJPY', '9m'),
        ('AUDJPY', '1y'),
        ('EURGBP',),
        ('GBPNZD',),
        ('EURCNH',),
        ('GBPCNH',),
        ('USDHKD',),
    ),
    'NZDUSD': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.756, 0.27, -0.955, -1.719),
        ('2W', 0.791, 0.2825, -1.0825, -1.9485),
        ('3W', 0.847, 0.3025, -1.24, -2.356),
        ('1M', 0.90625, 0.3125, -1.21, -2.299),
        ('2M', 1.05, 0.35, -1.34, -2.546),
        ('3M', 1.125, 0.375, -1.455, -2.7645),
        ('6M', 1.26325, 0.4075, -1.59, -3.021),
        ('9M', 1.333, 0.43, -1.65, -3.135),
        ('1Y', 1.416, 0.4425, -1.71, -3.249),
        ('2Y', 1.46125, 0.4175, -1.8525, -3.51975),
    ),
    'GBPUSD': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.5775, 0.1925, -0.445, -0.82325),
        ('2W', 0.6, 0.2, -0.5, -0.925),
        ('3W', 0.585, 0.195, -0.595, -1.10075),
        ('1M', 0.693, 0.22, -0.5825, -1.077625),
        ('2M', 0.80325, 0.255, -0.7425, -1.373625),
        ('3M', 0.928, 0.29, -0.8075, -1.493875),
        ('6M', 1.18625, 0.365, -0.94, -1.7625),
        ('9M', 1.3, 0.4, -1.08, -2.025),
        ('1Y', 1.411, 0.415, -1.12, -2.1),
        ('2Y', 1.462, 0.43, -1.2, -2.25),
    ),
    'GBPNZD': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.825, 0.22, 0.48, 0.624),
        ('2W', 0.834375, 0.2225, 0.505, 0.909),
        ('3W', 0.84375, 0.225, 0.52, 0.936),
        ('1M', 0.871875, 0.2325, 0.555, 0.999),
        ('2M', 0.95625, 0.255, 0.5625, 1.0125),
        ('3M', 1.126125, 0.2925, 0.5775, 1.0395),
        ('6M', 1.318625, 0.3425, 0.5575, 1.0035),
        ('9M', 1.52075, 0.395, 0.5875, 1.0575),
        ('1Y', 1.6, 0.4, 0.58, 1.044),
        ('2Y', 1.71175, 0.4175, 0.6625, 1.1925),
    ),
    'EURGBP': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.33325, 0.1075, 0.34, 0.612),
        ('2W', 0.3875, 0.125, 0.39, 0.702),
        ('3W', 0.465, 0.15, 0.425, 0.765),
        ('1M', 0.403, 0.13, 0.49, 0.9065),
        ('2M', 0.4805, 0.155, 0.575, 1.06375),
        ('3M', 0.558, 0.18, 0.6475, 1.197875),
        ('6M', 0.72075, 0.2325, 0.7875, 1.456875),
        ('9M', 0.79825, 0.2575, 0.8625, 1.595625),
        ('1Y', 0.84, 0.2625, 0.9125, 1.688125),
        ('2Y', 1.08, 0.3375, 0.8675, 1.604875),
    ),
    'USDHKD': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.6205, 0.1825, 0.385, 0.78925),
        ('2W', 0.6375, 0.1875, 0.45, 0.9675),
        ('1M', 0.731, 0.215, 0.525, 1.2075),
        ('2M', 0.816, 0.24, 0.66, 1.518),
        ('3M', 0.867, 0.255, 0.74, 1.702),
        ('6M', 0.986, 0.29, 0.95, 2.185),
        ('9M', 1.122, 0.33, 1.07, 2.461),
        ('1Y', 1.207, 0.355, 1.15, 2.645),
        ('2Y', 1.292, 0.38, 1.25, 2.875),
    ),
    'GBPCNH': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.703125, 0.1875, 0.095, 0.1235),
        ('2W', 0.73125, 0.195, 0.14, 0.252),
        ('3W', 0.75, 0.2, 0.145, 0.261),
        ('1M', 0.75, 0.2, 0.1575, 0.2835),
        ('2M', 0.834375, 0.2225, 0.185, 0.333),
        ('3M', 1.001, 0.26, 0.23, 0.414),
        ('6M', 1.155, 0.3, 0.355, 0.639),
        ('9M', 1.36675, 0.355, 0.375, 0.675),
        ('1Y', 1.45, 0.3625, 0.46, 0.828),
        ('2Y', 1.64, 0.4, 0.435, 0.783),
    ),
    'AUDCNH': (
    ),
    'NZDCNH': (
    ),
    'CNHHKD': (
    ),
    'EURCNH': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.476, 0.14, 0.0475, 0.1235),
        ('2W', 0.4675, 0.1375, 0.1225, 0.2205),
        ('1M', 0.5695, 0.1675, 0.26, 0.468),
        ('2M', 0.663, 0.195, 0.36, 0.648),
        ('3M', 0.765, 0.225, 0.4625, 0.8325),
        ('6M', 0.867, 0.255, 0.6775, 1.2195),
        ('9M', 1.02, 0.3, 0.57, 1.026),
        ('1Y', 1.122, 0.33, 0.925, 1.665),
        ('2Y', 1.207, 0.355, 1.1225, 2.0205),
    ),
    'AUDJPY': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.706875, 0.2175, -1.25, -2.28125),
        ('2W', 0.755625, 0.2325, -1.2925, -2.3588125),
        ('3W', 1.105, 0.34, -1.2975, -2.3679375),
        ('1M', 0.965625, 0.2575, -1.47, -2.68275),
        ('2M', 1.26, 0.315, -1.84, -3.358),
        ('3M', 1.41, 0.3525, -2.1575, -3.9374375),
        ('6M', 1.68, 0.42, -2.5675, -4.6856875),
        ('9M', 1.87, 0.4675, -2.735, -4.991375),
        ('1Y', 2.135625, 0.5025, -2.875, -5.246875),
        ('2Y', 2.295, 0.54, -3.34, -6.0955),
    ),
    'EURJPY': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.6175, 0.19, -0.43, -0.774),
        ('2W', 0.65, 0.2, -0.415, -0.747),
        ('3W', 0.6175, 0.19, -0.37, -0.666),
        ('1M', 0.76375, 0.235, -0.475, -0.855),
        ('2M', 0.869375, 0.2675, -0.6625, -1.1925),
        ('3M', 0.950625, 0.2925, -0.8275, -1.5101875),
        ('6M', 1.129375, 0.3475, -1.0925, -1.9938125),
        ('9M', 1.259375, 0.3875, -1.2925, -2.3588125),
        ('1Y', 1.291875, 0.3975, -1.3775, -2.5139375),
        ('2Y', 1.3975, 0.43, -1.685, -2.94875),
    ),
    'EURUSD': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.4425, 0.1475, -0.18, -0.315),
        ('2W', 0.4575, 0.1525, -0.165, -0.28875),
        ('3W', 0.4875, 0.1625, -0.1775, -0.310625),
        ('1M', 0.5175, 0.1725, -0.1225, -0.214375),
        ('2M', 0.585, 0.195, -0.1025, -0.179375),
        ('3M', 0.6375, 0.2125, -0.0925, -0.1665),
        ('6M', 0.8775, 0.27, -0.04, -0.072),
        ('9M', 1.04125, 0.2975, 0.0025, 0.0045625),
        ('1Y', 1.144875, 0.3225, 0.025, 0.04625),
        ('2Y', 1.207, 0.34, -0.055, -0.11825),
    ),
    'AUDUSD': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.8175, 0.2725, -0.9175, -1.6515),
        ('2W', 0.8775, 0.2925, -1.0425, -1.8765),
        ('3W', 0.93, 0.31, -1.205, -2.169),
        ('1M', 1.02, 0.34, -1.295, -2.363375),
        ('2M', 1.11, 0.37, -1.425, -2.600625),
        ('3M', 1.1925, 0.3975, -1.4875, -2.7146875),
        ('6M', 1.3125, 0.4375, -1.6475, -3.0066875),
        ('9M', 1.3575, 0.4525, -1.7175, -3.177375),
        ('1Y', 1.4025, 0.4675, -1.7675, -3.269875),
        ('2Y', 1.47, 0.49, -1.75, -3.2375),
    ),
    'USDJPY': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.6525, 0.2175, -0.0275, -0.050875),
        ('2W', 0.675, 0.225, -0.11, -0.2035),
        ('3W', 0.735, 0.245, -0.1475, -0.272875),
        ('1M', 0.72, 0.24, -0.24, -0.444),
        ('2M', 0.8025, 0.2675, -0.4575, -0.846375),
        ('3M', 0.87, 0.29, -0.645, -1.19325),
        ('6M', 0.99, 0.33, -0.9575, -1.915),
        ('9M', 1.065, 0.355, -1.0925, -2.0484375),
        ('1Y', 1.2025, 0.37, -1.19, -2.23125),
        ('2Y', 1.4525, 0.415, -1.42, -2.6625),
    ),
    'USDCNH': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.6205, 0.1825, 0.385, 0.78925),
        ('2W', 0.6375, 0.1875, 0.45, 0.9675),
        ('1M', 0.731, 0.215, 0.525, 1.2075),
        ('2M', 0.816, 0.24, 0.66, 1.518),
        ('3M', 0.867, 0.255, 0.74, 1.702),
        ('6M', 0.986, 0.29, 0.95, 2.185),
        ('9M', 1.122, 0.33, 1.07, 2.461),
        ('1Y', 1.207, 0.355, 1.15, 2.645),
        ('2Y', 1.292, 0.38, 1.25, 2.875),
    ),
    'USDCNY': (
        ('expiry', 'ST 10D', 'ST 25D', 'RR 25D', 'RR 10D'),
        ('1W', 0.546, 0.39, 0.5, 0.6),
        ('2W', 0.546, 0.39, 0.515, 0.618),
        ('1M', 0.546, 0.39, 0.55, 0.66),
        ('2M', 0.546, 0.39, 0.525, 0.63),
        ('3M', 0.6045, 0.39, 0.525, 0.6825),
        ('6M', 0.6435, 0.39, 0.6, 0.84),
        ('9M', 0.6825, 0.39, 0.625, 0.9375),
        ('1Y', 0.6825, 0.39, 0.65, 0.975),
        ('2Y', 0.6825, 0.39, 0.65, 0.975),
    ),
    'PARAMS': (
        (None, 'USDCNH', 'USDCNY', 'EURCNH', 'GBPCNH', 'USDJPY', 'EURUSD', 'AUDUSD', 'GBPUSD', 'NZDUSD', 'AUDJPY', 'EURJPY', 'GBPNZD', 'EURGBP', 'USDHKD'),
        ('initial', 4.9, 5, 0.42, 0.5, 6.05, 6.25, 10.9, 7.75, 10.9, 0.37, 0.405, 0.705, 0.57, 0.57),
        ('long term', 6.800000000000001, 4.95, 0.39, 0.375, 7.649999999999999, 6.950000000000001, 10.65, 9.03, 10.77, 0.19, 0.395, 0.54, 0.54, 0.54),
        ('ratevol', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
        ('addon', 0, -0.25, 0, 0.6, 0.7, 0.6, 1.1, 0.8, 1.2, 1.5, -0.2, 0, 0, 0),
        ('MR', 4.5, 3.5, 3, 3, 5, 6, 6.5, 6, 6.5, 5.5, 5, 4, 4, 4),
        ('rate corr', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
        ('short decay', 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50),
        ('anchor',),
    ),
    'EVENTS': (
        (None, 'AUD', 'CAD', 'CHF', 'CNH', 'EUR', 'GBP', 'NZD', 'USD', 'AUDJPY', 'AUDUSD', 'EURCNH', 'EURGBP', 'EURJPY', 'EURUSD', 'GBPCNH', 'GBPNZD', 'GBPUSD', 'NZDUSD', 'USDCNH', 'USDCNY', 'USDHKD', 'USDJPY'),
        (datetime.datetime(2024, 2, 2, 0, 0, 0), 3, 2, 1, 0.2, 0.9000000000000001, 2, 4, 6, None, 6.5, None, None, None, 5.5, None, None, 6, 6.5, 0.5, None, None, 5.5),
        (datetime.datetime(2024, 2, 2, 10, 0, 0), 3, 2, 1, 0.2, 0.9000000000000001, 2, 4, 1, None, 6.5, None, None, None, 5.5, None, None, 6, 6.5, 0.5, None, None, 5.5),
    ),
    'Vega Weights': (
        ('# How far each tenor moves when the anchor tenor moves one vol point.',),
        ("# 'default' is what every pair falls back to, cell by cell; a column headed by a pair is that pair's own shape. Only ratios matter -- the anchor's own weight cancels.",),
        ("# Marking screen > ATM term structure > bump; 'volkit vega <pair> --move 1'.",),
        ('tenor', 'default', 'USDCNH', 'note'),
        ('1W', None, 2.6),
        ('2W', None, 2.3),
        ('1M', None, 1.85),
        ('2M', None, 1.6),
        ('3M', None, 1.45),
        ('6M', None, 1.2),
        ('9M', None, 1.1),
        ('1Y', None, 1),
        ('2Y', None, 0.9),
        ('3Y', None, 0.85),
    ),
    'BANDS': (
        ('pair', 'mode', 'hazard', 'weak_share', 'weak_jump', 'weak_vol', 'strong_jump', 'strong_vol', 'lower', 'upper', 'blend', 'delta', 'solve_hazard'),
        ('USDHKD', 'warn', 2, 85, 6, 10, 4, 8, None, None, 100, 25, 0),
    ),
    'PEG_BANDS': (
        ('# Managed / pegged trading bands: pair, lower, upper, note.',),
        ('#',),
        ('# These are policy settings, not market data. Check them against the central',),
        ('# bank before use, and delete a pair whose regime changes.',),
        ('#',),
        ('# A band here means a HARD, defended range for the spot. Only list a pair on',),
        ('# this tab if that is true: the model gives strikes outside the band zero',),
        ('# in-band value, which is right for a defended peg and wrong for anything else.',),
        ('#',),
        ('# Not to be confused with the BANDS tab, which is the marking *treatment* for a',),
        ('# pegged pair -- hazard, jump sizes, blend. The defended range itself is here.',),
        ('pair', 'lower', 'upper', 'note'),
        ('USDHKD', 7.75, 7.85, 'HKMA Convertibility Undertakings under the Linked Exchange Rate System'),
        ('#',),
        ('# Deliberately NOT listed:',),
        ('#   USDCNY - the +/-2% limit is around a daily fixing, so the band moves every',),
        ('#            day and is not a fixed range for a multi-month option.',),
        ('#   USDCNH - offshore, not subject to the onshore limit at all.',),
        ('#   DKK    - ERM II central rate 7.46038 with a +/-2.25% formal band, but the',),
        ('#            Nationalbank runs a far tighter de facto range; add it only with',),
        ('#            a range you are prepared to defend.',),
    ),
    'KACE_SPREADS': (
        ('# The kACE feed: which tenors are posted as pillars, and the ATM bid/offer',),
        ('# width at each, in volatility points.  Read by volkit/kace.py.',),
        ('#',),
        ('# One row per tenor -- those are the pillars posted, so a tab with no rows',),
        ('# cannot be posted, and a tenor listed here with no wing marks in the',),
        ('# workbook is refused by name.  O/N is the one-day option and borrows the',),
        ("# shortest quoted tenor's wings.",),
        ('#',),
        ("# One column per spreading TIER: 'default', plus whatever else the desk",),
        ('# names.  A tier is a quoting policy and not a currency -- the pair is',),
        ('# chosen on the kACE feed screen beside the tier -- and a cell a tier',),
        ("# leaves blank takes 'default' for that tenor.  Tiers are added, edited",),
        ('# and removed in the Config window, and reach this file with the marks.',),
        ('#',),
        ('# A day between two pillars takes the spread of the earlier one; a day before',),
        ("# the O/N expiry takes O/N's.  The 'default' column is the USDCNH sheet's",),
        ('# column L, which is where this table started.',),
        ('tenor', 'default', 'wide', 'thin', 'note'),
        ('O/N', 1, 1.5, 0.6),
        ('1W', 0.8, 1.2, 0.5),
        ('2W', 0.6, 0.9, 0.4),
        ('1M', 0.4, 0.6, 0.25),
        ('2M', 0.3, 0.45, 0.2),
        ('3M', 0.3, 0.45, 0.2),
        ('6M', 0.2, 0.3, 0.15),
        ('9M', 0.2, 0.3, 0.15),
        ('1Y', 0.2, 0.3, 0.15),
    ),
    'HOLIDAYS': (
        ('# Holiday dates no rule derives: country, date, remove.',),
        ('#',),
        ('# Lunar-calendar holidays are published annually and cannot be worked out from',),
        ('# rules, so they are listed here. A row with remove = yes takes a date away',),
        ('# that the built-in rules would otherwise make a holiday.',),
        ('#',),
        ("# Dates are YYYY-MM-DD. A '#' in the first column makes the whole row a note.",),
        ('country', 'date', 'remove'),
        ('# Chinese New Year 2025',),
        ('CN', '2025-01-28'),
        ('CN', '2025-01-29'),
        ('CN', '2025-01-30'),
        ('CN', '2025-01-31'),
        ('CN', '2025-02-03'),
        ('CN', '2025-02-04'),
        ('# Chinese New Year 2026',),
        ('CN', '2026-02-16'),
        ('CN', '2026-02-17'),
        ('CN', '2026-02-18'),
        ('CN', '2026-02-19'),
        ('CN', '2026-02-20'),
    ),
}


#: The sheets that are a pair's quotes rather than a setting.  A pair is in
#: here if CONFIG names it, which is the same rule the reader uses.
PAIR_SHEETS = tuple(name for name in SHEETS if name in _CONFIG_PAIRS)


def make_workbook(path, pairs=None):
    """Write the test workbook to ``path`` and return it.

    ``pairs`` limits which pair sheets are written and trims CONFIG to match;
    the settings tabs -- CONFIG's own columns, PARAMS, EVENTS, BANDS,
    PEG_BANDS, KACE_SPREADS, HOLIDAYS, Vega Weights -- are always written whole,
    because they are what most tests are actually about.  A pair named here
    that the fixture does not carry is an error rather than a silently missing
    sheet, which is the failure this module exists to prevent.
    """
    path = Path(path)
    if pairs is not None:
        pairs = [p.upper() for p in pairs]
        missing = [p for p in pairs if p not in PAIR_SHEETS]
        if missing:
            raise KeyError(
                f"the fixture workbook has no sheet for {', '.join(missing)}; "
                f"it carries {', '.join(PAIR_SHEETS)}. Add the pair to "
                f"files/vol_marks.xlsx and re-run tests/_regenerate_fixture.py, "
                f"or build the sheet in the test with session.add_pair()."
            )
        keep = set(pairs)
    else:
        keep = set(PAIR_SHEETS)

    book = openpyxl.Workbook()
    book.remove(book.active)
    for name, rows in SHEETS.items():
        if name in PAIR_SHEETS and name not in keep:
            continue
        ws = book.create_sheet(name)
        if name == "CONFIG":
            rows = _config_rows(rows, keep)
        elif name == "EVENTS":
            rows = _drop_pair_columns(rows, keep)
        elif name == "BANDS":
            rows = _drop_pair_rows(rows, keep)
        for row in rows:
            ws.append(list(row))
    book.save(path)
    return path


def _config_rows(rows, keep):
    """CONFIG with the pairs that were left out taken out of its first column.

    CONFIG is not a table of records: each column is its own list, so column A
    is the pairs and column B is the tenor set, and the two have nothing to do
    with each other row by row.  Dropping a *row* to drop a pair therefore also
    drops whatever tenor happened to sit beside it -- which is how a workbook
    with two pairs ended up quoting two tenors.  The pairs are compacted up
    column A instead and every other column is left exactly where it was.
    """
    header, body = rows[0], [list(r) for r in rows[1:]]
    width = max((len(r) for r in body), default=1)
    kept = [r[0] for r in body
            if r and isinstance(r[0], str) and r[0].strip().upper() in keep]
    out = [header]
    for i, row in enumerate(body):
        row = row + [None] * (width - len(row))
        row[0] = kept[i] if i < len(kept) else None
        # A row that is now empty right across carries nothing; the sheet ends
        # where its longest column does, so trailing empties are dropped.
        out.append(tuple(row))
    while len(out) > 1 and all(c is None for c in out[-1]):
        out.pop()
    return out


def _drop_pair_columns(rows, keep):
    """EVENTS without the columns of pairs this workbook no longer builds.

    EVENTS is a column per currency and per pair.  Leaving a dropped pair's
    column in warns -- "a cell nothing reads is a bump nobody gets" -- which is
    true and is noise: the pair is missing because the test asked for a smaller
    book, not because the sheet is wrong. The currency columns are untouched.
    """
    if not rows:
        return rows
    header = rows[0]
    cut = {i for i, h in enumerate(header)
           if isinstance(h, str) and h.strip().upper() in _CONFIG_PAIRS
           and h.strip().upper() not in keep}
    if not cut:
        return rows
    return [tuple(c for i, c in enumerate(row) if i not in cut) for row in rows]


def _drop_pair_rows(rows, keep):
    """BANDS without the rows of pairs this workbook no longer builds.

    Same reason as the EVENTS columns: a band on a pair that is not in CONFIG
    is reported, correctly, and says nothing about the test that asked for two
    pairs instead of fourteen.
    """
    return [row for i, row in enumerate(rows)
            if i == 0 or not (isinstance(row[0], str)
                              and row[0].strip().upper() in _CONFIG_PAIRS
                              and row[0].strip().upper() not in keep)]
