"""Rewrite ``tests/_fixtures.py`` from ``files/vol_marks.xlsx``.

    python -m tests._regenerate_fixture

The suite must not read the shipped workbook for its numbers.  That file is a
spreadsheet: somebody exports the desk's own book over it, ten pairs appear, a
tenor column changes name, and a hundred tests that pinned numbers off it fail
for reasons that have nothing to do with the code.  It happened; it cost three
Windows builds.  So the numbers live here instead, as literals the tests own,
and this script is the only thing that copies them across -- deliberately, by a
person, in a commit that shows exactly which cells moved.

What it writes is every sheet's **values**, verbatim -- what a reader opening
the file with ``data_only=True`` sees, which is every reader volkit has.  No
sheet is larger than a screenful, so a faithful copy is a few hundred literals
rather than a summary that has to be trusted, and rebuilding from them gives a
workbook the readers cannot tell from the original.  That is what lets
``make_workbook()`` be a drop-in for copying the file.

The one thing it does not reproduce is that the 10-delta columns are *array
formulas* in the shipped sheet (``{=C2*3}``, with the value cached beside it).
openpyxl cannot write a formula and a cached value together, so the fixture
carries the cached numbers alone.  The handful of tests that are about the
formulas themselves -- that a copy keeps them, that a half-migrated sheet is
refused -- must keep reading ``files/vol_marks.xlsx``, and say so where they
do; they are testing the spreadsheet's shape, which is the one thing a fixture
cannot stand in for.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "files" / "vol_marks.xlsx"
TARGET = Path(__file__).resolve().parent / "_fixtures.py"

HEADER = '''"""The test workbook, as literals the suite owns.

Generated by ``tests/_regenerate_fixture.py`` from ``files/vol_marks.xlsx``.
Do not edit by hand: run that script, and commit the diff it makes.

``make_workbook(path)`` writes the whole thing, which is what the shipped file
says today, so a test that used to copy that file and pin numbers off it reads
the same numbers here.  ``make_workbook(path, pairs=("USDJPY", "EURUSD"))``
writes the settings tabs and only those pair sheets, which is the same workbook
as far as the settings go and a much smaller one to load: every reload
calibrates every pair in CONFIG, so a test that only marks USDJPY was paying
for thirteen other smiles on every read.
"""

from __future__ import annotations

import datetime
from pathlib import Path

import openpyxl

'''

FOOTER = '''

#: The sheets that are a pair's quotes rather than a setting.  A pair is in
#: here if CONFIG names it, which is the same rule the reader uses.
PAIR_SHEETS = tuple(name for name in SHEETS if name in _CONFIG_PAIRS)


def make_workbook(path, pairs=None):
    """Write the test workbook to ``path`` and return it.

    ``pairs`` limits which pair sheets are written and trims CONFIG to match;
    the settings tabs -- CONFIG's own columns, PARAMS, EVENTS, BANDS,
    PEG_BANDS, KACE_SPREADS, HOLIDAYS, Vega Weights -- are always written whole,
    because they are what most tests are actually about.  A pair named here
    that the fixture does not carry is an error rather than a silently missing
    sheet, which is the failure this module exists to prevent.
    """
    path = Path(path)
    if pairs is not None:
        pairs = [p.upper() for p in pairs]
        missing = [p for p in pairs if p not in PAIR_SHEETS]
        if missing:
            raise KeyError(
                f"the fixture workbook has no sheet for {', '.join(missing)}; "
                f"it carries {', '.join(PAIR_SHEETS)}. Add the pair to "
                f"files/vol_marks.xlsx and re-run tests/_regenerate_fixture.py, "
                f"or build the sheet in the test with session.add_pair()."
            )
        keep = set(pairs)
    else:
        keep = set(PAIR_SHEETS)

    book = openpyxl.Workbook()
    book.remove(book.active)
    for name, rows in SHEETS.items():
        if name in PAIR_SHEETS and name not in keep:
            continue
        ws = book.create_sheet(name)
        if name == "CONFIG":
            rows = _config_rows(rows, keep)
        elif name == "EVENTS":
            rows = _drop_pair_columns(rows, keep)
        elif name == "BANDS":
            rows = _drop_pair_rows(rows, keep)
        for row in rows:
            ws.append(list(row))
    book.save(path)
    return path


def _config_rows(rows, keep):
    """CONFIG with the pairs that were left out taken out of its first column.

    CONFIG is not a table of records: each column is its own list, so column A
    is the pairs and column B is the tenor set, and the two have nothing to do
    with each other row by row.  Dropping a *row* to drop a pair therefore also
    drops whatever tenor happened to sit beside it -- which is how a workbook
    with two pairs ended up quoting two tenors.  The pairs are compacted up
    column A instead and every other column is left exactly where it was.
    """
    header, body = rows[0], [list(r) for r in rows[1:]]
    width = max((len(r) for r in body), default=1)
    kept = [r[0] for r in body
            if r and isinstance(r[0], str) and r[0].strip().upper() in keep]
    out = [header]
    for i, row in enumerate(body):
        row = row + [None] * (width - len(row))
        row[0] = kept[i] if i < len(kept) else None
        # A row that is now empty right across carries nothing; the sheet ends
        # where its longest column does, so trailing empties are dropped.
        out.append(tuple(row))
    while len(out) > 1 and all(c is None for c in out[-1]):
        out.pop()
    return out


def _drop_pair_columns(rows, keep):
    """EVENTS without the columns of pairs this workbook no longer builds.

    EVENTS is a column per currency and per pair.  Leaving a dropped pair's
    column in warns -- "a cell nothing reads is a bump nobody gets" -- which is
    true and is noise: the pair is missing because the test asked for a smaller
    book, not because the sheet is wrong. The currency columns are untouched.
    """
    if not rows:
        return rows
    header = rows[0]
    cut = {i for i, h in enumerate(header)
           if isinstance(h, str) and h.strip().upper() in _CONFIG_PAIRS
           and h.strip().upper() not in keep}
    if not cut:
        return rows
    return [tuple(c for i, c in enumerate(row) if i not in cut) for row in rows]


def _drop_pair_rows(rows, keep):
    """BANDS without the rows of pairs this workbook no longer builds.

    Same reason as the EVENTS columns: a band on a pair that is not in CONFIG
    is reported, correctly, and says nothing about the test that asked for two
    pairs instead of fourteen.
    """
    return [row for i, row in enumerate(rows)
            if i == 0 or not (isinstance(row[0], str)
                              and row[0].strip().upper() in _CONFIG_PAIRS
                              and row[0].strip().upper() not in keep)]
'''


def literal(v):
    if isinstance(v, _dt.datetime):
        return (f"datetime.datetime({v.year}, {v.month}, {v.day}, "
                f"{v.hour}, {v.minute}, {v.second})")
    if isinstance(v, _dt.date):
        return f"datetime.date({v.year}, {v.month}, {v.day})"
    if isinstance(v, _dt.time):
        return f"datetime.time({v.hour}, {v.minute}, {v.second})"
    if isinstance(v, str) and v.startswith("="):
        raise SystemExit(
            f"a formula reached the value dump ({v!r}), which means the sheet "
            f"has no cached value for it -- the file was written by something "
            f"that does not compute. Open it in Excel and save, then re-run."
        )
    if not isinstance(v, (int, float, str, bool, type(None))):
        raise SystemExit(f"cell type {type(v).__name__} has no literal form yet: {v!r}")
    return repr(v)


def main() -> None:
    # data_only: the values Excel last computed, which is what every reader in
    # volkit opens the workbook with.  The formulas behind them are not
    # reproducible here (see the module docstring) and are counted, not copied.
    book = openpyxl.load_workbook(SOURCE, data_only=True)
    formulas = openpyxl.load_workbook(SOURCE)
    n_formula = sum(
        1
        for ws in formulas.worksheets
        for row in ws.iter_rows()
        for c in row
        if c.value is not None and not isinstance(c.value, (int, float, str, bool, _dt.date))
    )
    out = [HEADER]
    config_pairs = []
    ws = book["CONFIG"]
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row and isinstance(row[0], str) and row[0].strip():
            config_pairs.append(row[0].strip().upper())
    out.append("#: The pairs CONFIG names in the shipped workbook.\n")
    out.append("_CONFIG_PAIRS = frozenset({\n")
    for p in sorted(set(config_pairs)):
        out.append(f"    {p!r},\n")
    out.append("})\n\n")

    out.append("#: Every sheet, in the workbook's own order, as rows of cell values.\n")
    out.append("SHEETS = {\n")
    for ws in book.worksheets:
        out.append(f"    {ws.title!r}: (\n")
        rows = list(ws.iter_rows(values_only=True))
        while rows and all(c is None for c in rows[-1]):
            rows.pop()
        for row in rows:
            trimmed = list(row)
            while trimmed and trimmed[-1] is None:
                trimmed.pop()
            out.append("        (" + ", ".join(literal(c) for c in trimmed)
                       + ("," if len(trimmed) == 1 else "") + "),\n")
        out.append("    ),\n")
    out.append("}\n")
    out.append(FOOTER)
    TARGET.write_text("".join(out))
    print(f"wrote {TARGET.relative_to(ROOT)}  "
          f"({len(book.worksheets)} sheets, {len(config_pairs)} pairs in CONFIG, "
          f"{n_formula} formula cells written as their cached values)")


if __name__ == "__main__":
    main()
